-- Aquest script NOMÉS s'executa la primera vegada que es crea el contenidor.
-- Si es vol recrear les taules de nou cal esborrar el contenidor, o bé les dades del contenidor
-- és a dir, 
-- esborrar el contingut de la carpeta db_data 
-- o canviant el nom de la carpeta, però atenció a no pujar-la a git


-- És un exemple d'script per crear una base de dades i una taula
-- i afegir-hi dades inicials

-- Si creem la BBDD aquí podem control·lar la codificació i el collation
-- en canvi en el docker-compose no podem especificar el collation ni la codificació

-- Per assegurar-nes de que la codificació dels caràcters d'aquest script és la correcta
SET NAMES utf8mb4;

CREATE DATABASE IF NOT EXISTS persones
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

-- Donem permisos a l'usuari 'usuari' per accedir a la base de dades 'persones'
-- sinó, aquest usuari no podrà veure la base de dades i no podrà accedir a les taules
GRANT ALL PRIVILEGES ON persones.* TO 'usuari'@'%';
FLUSH PRIVILEGES;

-- Després de crear la base de dades, cal seleccionar-la per treballar-hi
USE persones;

CREATE TABLE TIPUS_INCIDENCIA(
  ID_TIPUS INT AUTO_INCREMENT PRIMARY KEY,
  DESCRIPCIO VARCHAR(50)
);

CREATE TABLE PRIORITAT(
  ID_PRIORITAT INT AUTO_INCREMENT PRIMARY KEY,
  DESCRIPCIO VARCHAR(50)
);

CREATE TABLE DEPARTAMENTS(
  ID_DEPARTAMENT INT AUTO_INCREMENT PRIMARY KEY,
  DESCRIPCIO VARCHAR(50)
);

CREATE TABLE TECNICS(
  ID_TECNIC INT AUTO_INCREMENT PRIMARY KEY,
  ID_DEPARTAMENT INT NOT NULL,
  NOM_TECNIC VARCHAR(50),
  ASSIGNACIONS INT DEFAULT 0,
  FOREIGN KEY (ID_DEPARTAMENT) REFERENCES DEPARTAMENTS(ID_DEPARTAMENT)
);
CREATE TABLE ESTAT (
  ID_ESTAT INT AUTO_INCREMENT PRIMARY KEY,
  DESCRIPCIO VARCHAR(50)

);
CREATE TABLE INCIDENCIES (
  ID_INCIDENCIA INT AUTO_INCREMENT PRIMARY KEY,
  ID_DEPARTAMENT INT NOT NULL,
  DATA_INICI DATE not null,
  DESCRIPCIO TEXT not null,
  ID_ESTAT INT NOT NULL DEFAULT 1,
  ORDINADOR INT NOT NULL,
  ID_TECNIC INT NOT NULL,
  ID_PRIORITAT INT NOT NULL DEFAULT 1,
  ID_TIPUS_INCIDENCIA INT NOT NULL DEFAULT 1,
  FOREIGN KEY (ID_TIPUS_INCIDENCIA) REFERENCES TIPUS_INCIDENCIA(ID_TIPUS),
  FOREIGN KEY (ID_DEPARTAMENT) REFERENCES DEPARTAMENTS(ID_DEPARTAMENT),
  FOREIGN KEY (ID_ESTAT) REFERENCES ESTAT(ID_ESTAT),
  FOREIGN KEY (ID_TECNIC) REFERENCES TECNICS(ID_TECNIC),
  FOREIGN KEY (ID_PRIORITAT) REFERENCES PRIORITAT(ID_PRIORITAT)
);

INSERT INTO TIPUS_INCIDENCIA (DESCRIPCIO) VALUES ('Sense Assignar');
INSERT INTO TIPUS_INCIDENCIA (DESCRIPCIO) VALUES ('Xarxa');
INSERT INTO TIPUS_INCIDENCIA (DESCRIPCIO) VALUES ('Ratolí');
INSERT INTO TIPUS_INCIDENCIA (DESCRIPCIO) VALUES ('Teclat');
INSERT INTO TIPUS_INCIDENCIA (DESCRIPCIO) VALUES ('Connexió a Internet');
INSERT INTO TIPUS_INCIDENCIA (DESCRIPCIO) VALUES ('Pantalla');
INSERT INTO TIPUS_INCIDENCIA (DESCRIPCIO) VALUES ('Software');
INSERT INTO TIPUS_INCIDENCIA (DESCRIPCIO) VALUES ('Servidor');
INSERT INTO TIPUS_INCIDENCIA (DESCRIPCIO) VALUES ('Correu Electrònic');

INSERT INTO PRIORITAT (DESCRIPCIO) VALUES ('Sense Assignar');
INSERT INTO PRIORITAT (DESCRIPCIO) VALUES ('Baixa');
INSERT INTO PRIORITAT (DESCRIPCIO) VALUES ('Mitjana');
INSERT INTO PRIORITAT (DESCRIPCIO) VALUES ('Alta');
INSERT INTO PRIORITAT (DESCRIPCIO) VALUES ('Crítica');

INSERT INTO DEPARTAMENTS (DESCRIPCIO) VALUES ('Matemàtiques');
INSERT INTO DEPARTAMENTS (DESCRIPCIO) VALUES ('Ciències Naturals');
INSERT INTO DEPARTAMENTS (DESCRIPCIO) VALUES ('Tecnologia');
INSERT INTO DEPARTAMENTS (DESCRIPCIO) VALUES ('Llengües');
INSERT INTO DEPARTAMENTS (DESCRIPCIO) VALUES ('Ciències Socials');
INSERT INTO DEPARTAMENTS (DESCRIPCIO) VALUES ('Educació Física');
INSERT INTO DEPARTAMENTS (DESCRIPCIO) VALUES ('Arts Plàstiques');
INSERT INTO DEPARTAMENTS (DESCRIPCIO) VALUES ('Música');
INSERT INTO DEPARTAMENTS (DESCRIPCIO) VALUES ('Informàtica');
INSERT INTO DEPARTAMENTS (DESCRIPCIO) VALUES ('Biblioteca');

INSERT INTO ESTAT (DESCRIPCIO) VALUES ('Assignada');
INSERT INTO ESTAT (DESCRIPCIO) VALUES ('En Procés');
INSERT INTO ESTAT (DESCRIPCIO) VALUES ('Acabada');

INSERT INTO TECNICS (ID_DEPARTAMENT,NOM_TECNIC) VALUES(1,'Miquel Garcia');
INSERT INTO TECNICS (ID_DEPARTAMENT, NOM_TECNIC) VALUES (2, 'Lautaro Garcia');
INSERT INTO TECNICS (ID_DEPARTAMENT, NOM_TECNIC) VALUES (3, 'Laura Torres');
INSERT INTO TECNICS (ID_DEPARTAMENT, NOM_TECNIC) VALUES (4, 'Jordi Puig');
INSERT INTO TECNICS (ID_DEPARTAMENT, NOM_TECNIC) VALUES (5, 'Anna Soler');
INSERT INTO TECNICS (ID_DEPARTAMENT, NOM_TECNIC) VALUES (6, 'Pau Vidal');
INSERT INTO TECNICS (ID_DEPARTAMENT, NOM_TECNIC) VALUES (7, 'Clara Riera');
INSERT INTO TECNICS (ID_DEPARTAMENT, NOM_TECNIC) VALUES (8, 'Marc Ferrer');
INSERT INTO TECNICS (ID_DEPARTAMENT, NOM_TECNIC) VALUES (9, 'Núria Pons');
INSERT INTO TECNICS (ID_DEPARTAMENT, NOM_TECNIC) VALUES (10, 'Oriol Martí');